### ISSUE TITLE
NTR: Request for S12 bill

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S12#9]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>bill <p><b>Definition</b><p> A projecting mouthpart found mainly in birds but also in turtle and other animals consisting of two bony projections (upper and lower mandibules) covered by a keratinized sheath of skin.   <p><H2> Optional </H2><p><b>Sources/references</b><p> https://en.wikipedia.org/wiki/Beak and other online resources e.g. https://www.britannica.com/science/beak<p> <b>Synonym or acronym (AltLabel)</b><p> beak<p><b>Mapping to other terminologies </b><p> http://purl.obolibrary.org/obo/UBERON_0005094 (sameAs)<p>

**Comment by gwemon** [comment]
In order to keep with the logic that if we are talking about the length of a body part then the body part needs to be defined in S12 then, after some reflection, I think that we need to treat "Culmen length" for bird morphometrics as the "Length of the bill culmen of a biological entity", i.e. bill culmen is the body part. Hence, I am also proposing to deprecate the current entry for S06 Length (culmen) and instead use the S06 for "Length" combined with a new "S12" for "bill culmen".
For OBIS parameters this would give us the P01: Length of biological entity specified elsewhere [Subcomponent: bill culmen].
Bill culmen would be defined as:  "The upper margin of the bill or beak of birds. Culmen length is a standard measurement in bird biometrics."

@nvs-vocabs/obis_vocabs do you agree? and if so do we still need to have an entry in S12 for "bill"?

**Comment by roswri** [comment]
Term created:
S1266 - bill: A projecting mouthpart found mainly in birds but also in turtles and other animals consisting of two bony projections (upper and lower mandibles) covered by a keratinised sheath of skin.
